name: build

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    test:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.0, 7.4, 7.3, 7.2 ]
                laravel: [ 9.*, 8.*, 7.*, 6.*, 5.8.*, 5.5.* ]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]
                include:
                    -   laravel: 9.*
                        testbench: 7.*
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*
                    -   laravel: 5.8.*
                        testbench: 3.*
                    -   laravel: 5.5.*
                        testbench: 3.*
                exclude:
                    -   laravel: 5.5.*
                        php: 8
                    -   laravel: 5.8.*
                        php: 8
                    -   laravel: 5.8.*
                        php: 8
                    -   laravel: 6.*
                        php: 7.2
                    -   laravel: 6.*
                        php: 8
                    -   laravel: 7.*
                        php: 7.2
                    -   laravel: 7.*
                        php: 8
                    -   laravel: 8.*
                        php: 7.2
                    -   laravel: 8.*
                        php: 7.3
                    -   laravel: 8.*
                        php: 7.4
                    -   laravel: 9.*
                        php: 7.2
                    -   laravel: 9.*
                        php: 7.3
                    -   laravel: 9.*
                        php: 7.4
        runs-on: ${{ matrix.os }}
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        env:
            extensions: intl, json, mbstring, dom, curl, openssl, mcrypt

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP extensions
                id: cache-env
                uses: shivammathur/cache-extensions@v1
                with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.extensions }}
                  key: php-extensions-cache-v1

            -   name: Setup PHP  ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.extensions }}
                    tools: composer
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Setup Laravel ${{ matrix.laravel }}
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Run tests
                run: "vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover"

            # Tenta enviar a cobertura de código até 5 vezes
            -   name: Upload coverage
                run: |
                    cover() {
                      curl -s https://scrutinizer-ci.com/ocular.phar -o ocular.phar
                      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
                    }
                    for i in {1..5}; do cover && break || sleep 5; done
                shell: bash
                continue-on-error: true

    update-docs:
        # Atualizar a documentação apenas a partir do ramo master
        needs: [ test ]
        if: "!contains(github.event.head_commit.message, 'skip ci') && github.ref == 'refs/heads/master'"
        runs-on: ubuntu-latest
        name: Update Docs
        steps:
            -   name: Checkout source
                uses: actions/checkout@v2
                with:
                    path: source

            -   name: Checkout gh-pages
                uses: actions/checkout@v2
                with:
                    ref: gh-pages
                    path: gh-pages

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    extensions: intl, mbstring, mcrypt, openssl

            -   name: Generate docs
                run: |
                    wget http://www.apigen.org/apigen.phar
                    php apigen.phar generate -s source/src -d tmp-doc --title 'Documentação laravel-boletos' --template-theme bootstrap
                continue-on-error: true

            # Remove todos arquivos antigos e adiciona os novos
            -   name: Publish
                working-directory: gh-pages
                run: |
                    rm -rf *
                    cp -r ../tmp-doc/. ./
                    git config user.name github-actions
                    git config user.email github-action@users.noreply.github.com
                    git add .
                    git commit -m "Documentacao atualizada"
                    git push
                continue-on-error: true
